name: cordex-aws
channels:
  - conda-forge
dependencies:
  - cryptography=37.0.2
  - esgf-pyclient
  - s3fs
  - xarray
  - dask
  - netCDF4
  - pangeo-forge-recipes=0.9.0
  - pip:
    #- git+https://github.com/larsbuntemeyer/pangeo-forge-esgf.git@cordex-requests
    - git+https://github.com/euro-cordex/pangeo-forge-cordex.git
